export type ColumnType =
    | 'text'
    | 'varchar'
    | 'integer'
    | 'bigint'
    | 'boolean'
    | 'jsonb'
    | 'json'
    | 'timestamptz'
    | 'timestamp'
    | 'interval';

export interface ColumnSchema {
    name: string;
    label: string;
    type: ColumnType;
    primaryKey?: boolean;
    autoGenerated?: boolean;
    nullable?: boolean;
    searchable?: boolean;
    hidden?: boolean;
    truncate?: number;
}

export interface TableSchema {
    name: string;
    label: string;
    primaryKey: string;
    columns: ColumnSchema[];
}

export const TABLE_SCHEMAS: TableSchema[] = [
    {
        name: 'sources',
        label: 'Sources',
        primaryKey: 'id',
        columns: [
            { name: 'id', label: 'ID', type: 'bigint', primaryKey: true, autoGenerated: true },
            { name: 'name', label: 'Název', type: 'text', searchable: true },
            { name: 'base_url', label: 'Base URL', type: 'text', searchable: true, truncate: 60 },
            { name: 'enabled', label: 'Aktivní', type: 'boolean' },
            { name: 'crawl_strategy', label: 'Strategie', type: 'text' },
            { name: 'crawl_params', label: 'Crawl Params', type: 'jsonb', nullable: true, truncate: 40 },
            { name: 'extraction_data', label: 'Extraction Data', type: 'jsonb', nullable: true, truncate: 40 },
            { name: 'crawl_interval', label: 'Interval', type: 'interval', nullable: true },
            { name: 'last_crawled_at', label: 'Poslední crawl', type: 'timestamptz', nullable: true },
            { name: 'created_at', label: 'Vytvořeno', type: 'timestamptz', autoGenerated: true },
            { name: 'updated_at', label: 'Upraveno', type: 'timestamptz', autoGenerated: true },
            { name: 'kraj_id', label: 'Kraj ID', type: 'text', nullable: true },
            { name: 'okres_id', label: 'Okres ID', type: 'text', nullable: true },
            { name: 'obec_id', label: 'Obec ID', type: 'integer', nullable: true },
            { name: 'typ_id', label: 'Typ ID', type: 'integer', nullable: true },
        ],
    },
    {
        name: 'source_urls',
        label: 'Source URLs',
        primaryKey: 'id',
        columns: [
            { name: 'id', label: 'ID', type: 'bigint', primaryKey: true, autoGenerated: true },
            { name: 'source_id', label: 'Source ID', type: 'bigint' },
            { name: 'url', label: 'URL', type: 'text', searchable: true, truncate: 80 },
            { name: 'label', label: 'Popis', type: 'text', nullable: true, searchable: true },
            { name: 'enabled', label: 'Aktivní', type: 'boolean' },
            { name: 'created_at', label: 'Vytvořeno', type: 'timestamptz', autoGenerated: true },
            { name: 'updated_at', label: 'Upraveno', type: 'timestamptz', autoGenerated: true },
        ],
    },
    {
        name: 'source_types',
        label: 'Source Types',
        primaryKey: 'id',
        columns: [
            { name: 'id', label: 'ID', type: 'integer', primaryKey: true, autoGenerated: true },
            { name: 'name', label: 'Název', type: 'text', searchable: true },
            { name: 'created_at', label: 'Vytvořeno', type: 'timestamptz', autoGenerated: true },
        ],
    },
    {
        name: 'documents',
        label: 'Documents',
        primaryKey: 'id',
        columns: [
            { name: 'id', label: 'ID', type: 'bigint', primaryKey: true, autoGenerated: true },
            { name: 'source_url_id', label: 'Source URL ID', type: 'bigint' },
            { name: 'url', label: 'URL', type: 'text', searchable: true, truncate: 80 },
            { name: 'filename', label: 'Soubor', type: 'text', nullable: true, searchable: true },
            { name: 'checksum', label: 'Checksum', type: 'text', truncate: 20 },
            { name: 'last_seen_at', label: 'Naposledy viděn', type: 'timestamptz' },
            { name: 'current_text_id', label: 'Text ID', type: 'bigint', nullable: true },
            { name: 'created_at', label: 'Vytvořeno', type: 'timestamptz', autoGenerated: true },
            { name: 'updated_at', label: 'Upraveno', type: 'timestamptz', autoGenerated: true },
            { name: 'deleted_at', label: 'Smazáno', type: 'timestamptz', nullable: true },
            { name: 'meta', label: 'Meta', type: 'jsonb', nullable: true, truncate: 40 },
            { name: 'updates_history', label: 'Historie', type: 'jsonb', nullable: true, hidden: true },
            { name: 'external_storage', label: 'Ext. Storage', type: 'jsonb', nullable: true, hidden: true },
        ],
    },
    {
        name: 'document_texts',
        label: 'Document Texts',
        primaryKey: 'id',
        columns: [
            { name: 'id', label: 'ID', type: 'bigint', primaryKey: true, autoGenerated: true },
            { name: 'document_id', label: 'Document ID', type: 'bigint' },
            { name: 'version', label: 'Verze', type: 'integer' },
            { name: 'ocr_engine', label: 'OCR Engine', type: 'text', nullable: true },
            { name: 'ocr_language', label: 'OCR Jazyk', type: 'text', nullable: true },
            { name: 'text', label: 'Text', type: 'text', nullable: true, truncate: 100 },
            { name: 'created_at', label: 'Vytvořeno', type: 'timestamptz', autoGenerated: true },
        ],
    },
    {
        name: 'ingestion_items',
        label: 'Ingestion Items',
        primaryKey: 'id',
        columns: [
            { name: 'id', label: 'ID', type: 'bigint', primaryKey: true, autoGenerated: true },
            { name: 'run_id', label: 'Run ID', type: 'bigint', nullable: true },
            { name: 'document_id', label: 'Document ID', type: 'bigint' },
            { name: 'source_url_id', label: 'Source URL ID', type: 'bigint' },
            { name: 'document_url', label: 'URL', type: 'text', searchable: true, truncate: 80 },
            { name: 'filename', label: 'Soubor', type: 'text', nullable: true, searchable: true },
            { name: 'file_checksum', label: 'Checksum', type: 'text', truncate: 20 },
            { name: 'file_kind', label: 'Typ souboru', type: 'text' },
            { name: 'ingest_status', label: 'Status', type: 'text' },
            { name: 'ingest_reason', label: 'Důvod', type: 'text', nullable: true },
            { name: 'signature', label: 'Podpis', type: 'text', nullable: true, truncate: 30 },
            { name: 'payload_json', label: 'Payload', type: 'json', nullable: true, hidden: true },
            { name: 'last_job_key', label: 'Job Key', type: 'text', nullable: true },
            { name: 'received_at', label: 'Přijato', type: 'timestamp' },
            { name: 'created_at', label: 'Vytvořeno', type: 'timestamp', autoGenerated: true },
            { name: 'updated_at', label: 'Upraveno', type: 'timestamp', autoGenerated: true },
            { name: 'error_message', label: 'Chyba', type: 'text', nullable: true, truncate: 60 },
        ],
    },
    {
        name: 'ingestion_runs',
        label: 'Ingestion Runs',
        primaryKey: 'id',
        columns: [
            { name: 'id', label: 'ID', type: 'bigint', primaryKey: true, autoGenerated: true },
            { name: 'source_url_id', label: 'Source URL ID', type: 'bigint' },
            { name: 'started_at', label: 'Zahájeno', type: 'timestamp' },
            { name: 'finished_at', label: 'Dokončeno', type: 'timestamp', nullable: true },
            { name: 'status', label: 'Status', type: 'text' },
            { name: 'stats_json', label: 'Statistiky', type: 'json', nullable: true, truncate: 40 },
            { name: 'created_by', label: 'Vytvořil', type: 'text' },
            { name: 'created_at', label: 'Vytvořeno', type: 'timestamp', autoGenerated: true },
        ],
    },
    {
        name: 'cz_regions_kraj',
        label: 'Kraje',
        primaryKey: 'id',
        columns: [
            { name: 'id', label: 'ID', type: 'text', primaryKey: true },
            { name: 'code', label: 'Kód', type: 'text', searchable: true },
            { name: 'nuts3_code', label: 'NUTS3', type: 'text' },
            { name: 'name', label: 'Název', type: 'jsonb', searchable: true },
            { name: 'created_at', label: 'Vytvořeno', type: 'timestamptz', autoGenerated: true },
        ],
    },
    {
        name: 'cz_regions_okres',
        label: 'Okresy',
        primaryKey: 'id',
        columns: [
            { name: 'id', label: 'ID', type: 'text', primaryKey: true },
            { name: 'code', label: 'Kód', type: 'text', searchable: true },
            { name: 'lau_code', label: 'LAU', type: 'text' },
            { name: 'name', label: 'Název', type: 'jsonb', searchable: true },
            { name: 'kraj_id', label: 'Kraj ID', type: 'text' },
            { name: 'created_at', label: 'Vytvořeno', type: 'timestamptz', autoGenerated: true },
        ],
    },
    {
        name: 'cz_regions_obec',
        label: 'Obce',
        primaryKey: 'id',
        columns: [
            { name: 'id', label: 'ID', type: 'text', primaryKey: true },
            { name: 'kod', label: 'Kód', type: 'text', searchable: true },
            { name: 'nazev', label: 'Název', type: 'jsonb', searchable: true },
            { name: 'okres_id', label: 'Okres ID', type: 'text' },
            { name: 'created_at', label: 'Vytvořeno', type: 'timestamptz', autoGenerated: true },
            { name: 'orp_id', label: 'ORP ID', type: 'integer' },
        ],
    },
    {
        name: 'users',
        label: 'Uživatelé',
        primaryKey: 'id',
        columns: [
            { name: 'id', label: 'ID', type: 'bigint', primaryKey: true, autoGenerated: true },
            { name: 'email', label: 'Email', type: 'varchar', searchable: true },
            { name: 'password_hash', label: 'Heslo (hash)', type: 'text', hidden: true },
            { name: 'roles', label: 'Role', type: 'json' },
            { name: 'is_active', label: 'Aktivní', type: 'boolean' },
            { name: 'created_at', label: 'Vytvořeno', type: 'timestamp', autoGenerated: true },
            { name: 'updated_at', label: 'Upraveno', type: 'timestamp', autoGenerated: true },
            { name: 'permissions', label: 'Oprávnění', type: 'json' },
        ],
    },
    {
        name: 'doctrine_migration_versions',
        label: 'Migrace',
        primaryKey: 'version',
        columns: [
            { name: 'version', label: 'Verze', type: 'varchar', primaryKey: true, searchable: true },
            { name: 'executed_at', label: 'Provedeno', type: 'timestamp', nullable: true },
            { name: 'execution_time', label: 'Čas (ms)', type: 'integer', nullable: true },
        ],
    },
];

export const ALLOWED_TABLES = TABLE_SCHEMAS.map(t => t.name);

export function getTableSchema(tableName: string): TableSchema | undefined {
    return TABLE_SCHEMAS.find(t => t.name === tableName);
}

export function getVisibleColumns(schema: TableSchema): ColumnSchema[] {
    return schema.columns.filter(c => !c.hidden);
}

export function getCreateColumns(schema: TableSchema): ColumnSchema[] {
    return schema.columns.filter(c => !c.autoGenerated);
}

export function getEditColumns(schema: TableSchema): ColumnSchema[] {
    return schema.columns.filter(c => !c.autoGenerated && !c.primaryKey);
}

export function formatCellValue(value: unknown, col: ColumnSchema): string {
    if (value === null || value === undefined) return '—';

    switch (col.type) {
        case 'jsonb':
        case 'json': {
            if (typeof value === 'object') {
                const obj = value as Record<string, unknown>;
                if (obj.cs) return String(obj.cs);
                if (obj.cz) return String(obj.cz);
                const str = JSON.stringify(value);
                return col.truncate && str.length > col.truncate
                    ? str.slice(0, col.truncate) + '...'
                    : str;
            }
            return String(value);
        }
        case 'boolean':
            return value ? 'Ano' : 'Ne';
        case 'timestamptz':
        case 'timestamp':
            try {
                return new Date(value as string).toLocaleString('cs-CZ');
            } catch {
                return String(value);
            }
        default: {
            const str = String(value);
            return col.truncate && str.length > col.truncate
                ? str.slice(0, col.truncate) + '...'
                : str;
        }
    }
}
